### ISSUE TITLE
ActionUI hotkeys aren't saved

### ISSUE THREAD

**Issue by YourCompanionCube** [ModifAmorphic/outward#59]
after the latest update of ActionUI whenever i go back to the main menu and reload all my hotkeys are reset to default, my bars and what's in them are saved properly but the binding are not

**Comment by ModifAmorphic** [comment]
Thanks for reporting this. I have not been able to reproduce this though on version 1.0.1.  Tried a few different things:

1. Loaded Save
2. Set Bindings
3. Back to Main Menu
4. Continue Character.
Result: Key Bindings Not Reset

1. Loaded Save
2. Viewed Bindings
3. Back to Main Menu
4. Continue with different Character.
5. Bindings not Reset
6. Back to Main Menu
7. Continue with character in step 1.
8. Bindings not Reset

**Comment by YourCompanionCube** [comment]
Reinstalled (and updated to 1.0.4) using r2modman and still have this issue, both on existing characters and on a new testing one

First attempt
``` 
1. Loaded save
2. Set bindings
3. Back to main menu
4. Continue character
Result: default keybindings
```
Second attempt
```
1. New game
2. Set new keybinds
3. Back to main Menu
4. continue character
Result: default keybindings
```
only things i have installed other than this and dependencies is Raid Mode

**Comment by ModifAmorphic** [comment]
Unable to create in latest versions. Closing.
