### ISSUE TITLE
Assign scroll wheel up and down as hotkey

### ISSUE THREAD

**Issue by maliklatreille** [ModifAmorphic/outward#73]
Hey, it would be nice if you could assigne the scroll wheel up and down as hotkeys for Action UI. I was thinking of using the scroll wheel to cycle through the next and previous hotbars. I tried setting it but it didn't seem to want to capture scroll up and down.

**Comment by ModifAmorphic** [comment]
Great suggestion. Added in release [ActionUI v1.1.5](https://github.com/ModifAmorphic/outward/releases/tag/ActionUI-v1.1.5).

**Comment by maliklatreille** [comment]
Thanks for adding my suggestion! Keep up the great work. This is an awesome mod.
